---
- hosts: all
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - docker.io
        - python3-pip

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Set up testing environment
      apt:
        name: python3-venv
        state: present
